#include <stdio.h>
#include <unistd.h>
#include <bpf/libbpf.h>
#include "hello.skel.h"

// captures all internal debug, warning, and error messages 
// generated by libbpf and prints them to stderr
static int libbpf_print_fn(enum libbpf_print_level level, const char *format, va_list args) {
    return vfprintf(stderr, format, args);
}

int main(int argc, char **argv) {
    struct hello_bpf *skel;
    int err;

    // executes the logging function
    libbpf_set_print(libbpf_print_fn);

    // open and load the BPF program
    // (does a lot of things in the background)
    skel = hello_bpf__open_and_load();
    if (!skel) {
        fprintf(stderr, "Failed to open and load BPF skeleton\n");
        return 1;
    }

    // reads the macro in hello.bpf.c and hooks
    // the program to specific event (sys_enter_openat)
    err = hello_bpf__attach(skel);
    if (err) {
        fprintf(stderr, "Failed to attach BPF skeleton\n");
        hello_bpf__destroy(skel);
        return 1;
    }

    printf("libbpf successfully attached to openat\n");
    printf("Read trace logs using: sudo cat /sys/kernel/debug/tracing/trace_pipe\n");
    printf("Press Ctrl+C to stop...\n");

    while (1) {
        sleep(1);
    }

    hello_bpf__destroy(skel);
    return 0;
}